### ISSUE TITLE
widget-mediator.zopim.com - Possible false positive

### ISSUE THREAD

**Issue by p1r473** [bjornstar/hosts#13]
Hello,
I have whitelisted widget-mediator.zopim.com on my end as I believe it may be a false positive
It breaks the "chat with support" widgets on sites such as ship.reship.com
Opening this ticket in case you want to remove it on your end

**Comment by bjornstar** [comment]
Thanks for creating an issue. 

I really dislike "Chat with support" widgets especially when they are 3rd party. If you like them, that's cool.
