### ISSUE TITLE
livestream.com

### ISSUE THREAD

**Issue by p1r473** [bjornstar/hosts#14]
Hello,
livestream.com may be a false positive.
It is used for streaming online to an audience.
I have whitelisted on my end, but opening this ticket to inform you it may be a FP.

**Comment by bjornstar** [comment]
Could you give me a link where it is used in a non-advertising way?

**Comment by p1r473** [comment]
Was trying to watch https://app.hedgeye.com/insights/83890-webcast-navigating-the-next-chapter-of-this-market-crisis-david-ros
