### ISSUE TITLE
reg34.smp.ne.jp

### ISSUE THREAD

**Issue by Kebigon** [bjornstar/hosts#16]
Hi,

It seems to me that reg34.smp.ne.jp is a false positive, it is used to host Japanese loan-related forms.

Sincerely,
Kebigon

**Comment by bjornstar** [comment]
Could you provide a link where it is used in a non-advertising way?

**Comment by Kebigon** [comment]
Hi Bjornstar,

Sure, please find below two examples of forms hosted at this address:
* [Example 1](https://reg34.smp.ne.jp/regist/is?SMPFORM=lbpd-rflgt-92e561f5f7d074d336e6ffe75d3b6759)
* [Example 2](https://reg34.smp.ne.jp/regist/is?SMPFORM=lbpd-obmdn-f685b9e1543d92914022d5f9f85f6052)

Please let me know if you need any additional details.

Sincerely,
Kebigon

**Comment by bjornstar** [comment]
Ok, I see it linked from https://www.jasso.go.jp/shogakukin/henkan/furikae/kozahenko.html

These 3rd party forms are really bad practice, but I'll take it off the list.

**Comment by Kebigon** [comment]
Thank you
