### ISSUE TITLE
spotify.com

### ISSUE THREAD

**Issue by FadeMind** [bjornstar/hosts#3]
CC @bjornstar  @StevenBlack

Why did you blocking whole spotify services?? :scream: 

Please Whitelist these domains:
```
0.0.0.0 embed.spotify.com
0.0.0.0 www.spotify.com
0.0.0.0 developer.spotify.com
0.0.0.0 play.spotify.com
0.0.0.0 open.spotify.com
0.0.0.0 play.spotify.edgekey.net
```
Thanks

FM

**Comment by bjornstar** [comment]
I'm not a fan of spotify, having their unusable embeds all over the web drives me crazy. You're free to put them on your whitelist. If you want to remove my list because I have spotify on there, go ahead. I'm happy to have spotify blocked.

**Comment by FadeMind** [comment]
@bjornstar alredy did this :package:  >> 
https://github.com/FadeMind/mnjpkgbuilds/blob/master/00-HSTS.EXT/whitelist

BUT IDK what thinking @stevenblack about this policy :thinking:

**Comment by StevenBlack** [comment]
Hi @bjornstar there's a difference between artfully blocking Spotify, and completely blocking the service.  It's one of the top music streaming sites in the world...

Can I make a suggestion for the list?  How about sorting it?  This would make it easier to eyeball.  I reckon it's harder to curate a list you can't scan...

**Comment by bjornstar** [comment]
Hi @StevenBlack While you might say it's artless to block spotify completely, they blocked the entire country I was living in when I put them on my list. That said, I don't expect to change anyone's mind on the usefulness of spotify.

Thank you for your suggestion. I've gone ahead and sorted the domains. It certainly is easier on the eyes now.

I'm also a bit unclear about the policies for your lists, it might be helpful to write something down about what should and should not be included.

Thanks for taking the time to look at my list!
