### ISSUE TITLE
False positive

### ISSUE THREAD

**Issue by mkb2091** [bjornstar/hosts#4]
I found www.digicert.com is blocked by your hostfile, but it is a SSL certificate authority, not an advert, so I think it is a false positive

**Comment by preachermanx** [comment]
Depends on how many horrible ads they have been posting recently. :)

**Comment by bjornstar** [comment]
Typically cert vendors get put on the list because they encourage people to put advertisements on their sites but they call them "seals" instead of advertisements.

Feel free to put them on your whitelist, I have no desire to see their ads.
