### ISSUE TITLE
privateinternetaccess 

### ISSUE THREAD

**Issue by CitizenXVIL** [bjornstar/hosts#5]
Out of curiosity, why is privateinternetaccess.com on your list?

**Comment by bjornstar** [comment]
Typically domains get onto this list by showing up on third party sites or by existing solely to track users or display ads.

Looking at the commit that added them (https://github.com/bjornstar/hosts/commit/bb34d32e3f3567bae3eaf97b3be6a204b00e7772) I'd guess they advertised on some site.

If you think they don't deserve to be on this list, I wouldn't mind removing them.

**Comment by bjornstar** [comment]
Feel free to reopen if it's still an issue.
