### ISSUE TITLE
Google AMP

### ISSUE THREAD

**Issue by DRSDavidSoft** [bjornstar/hosts#7]
Is the amp project intentionally blocked?
https://github.com/bjornstar/hosts/blob/9d3694d3d4b513aaf91e2f3af96bb27fc6b2687b/hosts#L5760

This entry causes domains like reddit's amp to not work.

added via 83fa25bc8189036784072087a5e85ca1037b86f8

**Comment by bjornstar** [comment]
Yes it is. I think AMP is making the web worse. If you wait 8 seconds on reddit, the content will appear. It's intentionally hidden from view for 8 seconds by the AMP standard.

Here's an example:
https://amp.reddit.com/r/askscience/comments/53oaf7/discussion_minuteearths_newest_youtube_video_on/

Just wait 8 seconds.

This is why AMP needs to go away.

**Comment by DRSDavidSoft** [comment]
While I agree with you on the fact that AMP is useless junk, I'm not exactly sure if I'm following you correctly.

Do you mean that there's some sort of redirect from the AMP version to the original page? I'm 90% sure that this doesn't happen in my device 🤷

In any case, thank you for the explanation. I appreciate getting into the details for blocks such as this :)

**Comment by bjornstar** [comment]
I mean that there is a CSS rule that hides the content for 8 seconds.

``` html
      <style amp-boilerplate="">
        body{-webkit-animation:-amp-start 8s steps(1,end) 0s 1 normal
        both;-moz-animation:-amp-start 8s steps(1,end) 0s 1 normal both;-ms-animation:-amp-start
        8s steps(1,end) 0s 1 normal both;animation:-amp-start 8s steps(1,end) 0s 1
        normal both}@-webkit-keyframes
        -amp-start{from{visibility:hidden}to{visibility:visible}}@-moz-keyframes
        -amp-start{from{visibility:hidden}to{visibility:visible}}@-ms-keyframes
        -amp-start{from{visibility:hidden}to{visibility:visible}}@-o-keyframes
        -amp-start{from{visibility:hidden}to{visibility:visible}}@keyframes
        -amp-start{from{visibility:hidden}to{visibility:visible}}
      </style>
```

This is "required" by the AMP specification.

**Comment by DRSDavidSoft** [comment]
Wow, I didn't notice that. This part of the specifications is the most idiotic thing I've seen!

Thank you for the clarification

**Comment by p1r473** [comment]
Didnt know this, thanks.
