### ISSUE TITLE
images.ctfassets.net

### ISSUE THREAD

**Issue by DRSDavidSoft** [bjornstar/hosts#8]
The domain name `images.ctfassets.net` belongs to the [Contentful CMS](https://www.contentful.com/) assets.

Is this intentionally blocked? It was added via 2da38aad0e070f271e64bddb89d6ea9b238160c2 and I don't believe this domain is intended to be blocked.

**Comment by bjornstar** [comment]
I add every host to this list by hand. It looks like it was used by some spam sites.

I'd be happy to remove it from the list if that's what you're asking for.

**Comment by DRSDavidSoft** [comment]
Since it's also used to serve non-spam content, I'd appreciate if you did so!

**Comment by Peezy89** [comment]
How would I know what going on I’m new here

**Comment by Peezy89** [comment]
Can somebody please tell me images.ctfassets.net #8 is please I need to know asap
